### ISSUE TITLE
html方案怎么实现js公共提取

### ISSUE THREAD

**Issue by yuancongcong** [hubcarl/easywebpack-multiple-html-boilerplate#5]

**Comment by hubcarl** [comment]
https://github.com/easy-team/easywebpack-html/issues/2

**Comment by hubcarl** [comment]
@yuancongcong  公共提取通过 webpack optimization 配置实现，具体看这个配置，关键是 minChunks的 配置。 https://www.yuque.com/easy-team/easywebpack/optimizaiton

**Comment by yuancongcong** [comment]
> @yuancongcong 公共提取通过 webpack optimization 配置实现，具体看这个配置，关键是 minChunks的 配置。 https://www.yuque.com/easy-team/easywebpack/optimizaiton

解决了 thanks!
